// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.11.3
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace WorkQueue.topic.v1
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.11.3")]
	public partial class WorkQueue : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse(@"{""type"":""record"",""name"":""WorkQueue"",""namespace"":""WorkQueue.topic.v1"",""fields"":[{""name"":""eventType"",""default"":null,""type"":[""null"",""string""]},{""name"":""opType"",""default"":null,""type"":[""null"",""string""]},{""name"":""cdhTerminalCode"",""default"":null,""type"":[""null"",""string""]},{""name"":""messageSequenceNumber"",""default"":null,""type"":[""null"",""long""]},{""name"":""workQueueId"",""default"":null,""type"":[""null"",""long""]},{""name"":""vesselVisitId"",""default"":null,""type"":[""null"",""string""]},{""name"":""vesselName"",""default"":null,""type"":[""null"",""string""]},{""name"":""vesselRow"",""default"":null,""type"":[""null"",""string""]},{""name"":""vesselDeck"",""default"":null,""type"":[""null"",""string""]},{""name"":""workQueueName"",""default"":null,""type"":[""null"",""string""]},{""name"":""workQueueStatus"",""default"":null,""type"":[""null"",""string""]},{""name"":""workQueueSequence"",""default"":null,""type"":[""null"",""string""]},{""name"":""workQueueType"",""default"":null,""type"":[""null"",""string""]},{""name"":""pointOfWorkName"",""default"":null,""type"":[""null"",""string""]},{""name"":""load_mode"",""default"":null,""type"":[""null"",""string""]},{""name"":""SOURCE_TS_MS"",""default"":null,""type"":[""null"",""long""]}]}");
		private string _eventType;
		private string _opType;
		private string _cdhTerminalCode;
		private System.Nullable<System.Int64> _messageSequenceNumber;
		private System.Nullable<System.Int64> _workQueueId;
		private string _vesselVisitId;
		private string _vesselName;
		private string _vesselRow;
		private string _vesselDeck;
		private string _workQueueName;
		private string _workQueueStatus;
		private string _workQueueSequence;
		private string _workQueueType;
		private string _pointOfWorkName;
		private string _load_mode;
		private System.Nullable<System.Int64> _SOURCE_TS_MS;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return WorkQueue._SCHEMA;
			}
		}
		public string eventType
		{
			get
			{
				return this._eventType;
			}
			set
			{
				this._eventType = value;
			}
		}
		public string opType
		{
			get
			{
				return this._opType;
			}
			set
			{
				this._opType = value;
			}
		}
		public string cdhTerminalCode
		{
			get
			{
				return this._cdhTerminalCode;
			}
			set
			{
				this._cdhTerminalCode = value;
			}
		}
		public System.Nullable<System.Int64> messageSequenceNumber
		{
			get
			{
				return this._messageSequenceNumber;
			}
			set
			{
				this._messageSequenceNumber = value;
			}
		}
		public System.Nullable<System.Int64> workQueueId
		{
			get
			{
				return this._workQueueId;
			}
			set
			{
				this._workQueueId = value;
			}
		}
		public string vesselVisitId
		{
			get
			{
				return this._vesselVisitId;
			}
			set
			{
				this._vesselVisitId = value;
			}
		}
		public string vesselName
		{
			get
			{
				return this._vesselName;
			}
			set
			{
				this._vesselName = value;
			}
		}
		public string vesselRow
		{
			get
			{
				return this._vesselRow;
			}
			set
			{
				this._vesselRow = value;
			}
		}
		public string vesselDeck
		{
			get
			{
				return this._vesselDeck;
			}
			set
			{
				this._vesselDeck = value;
			}
		}
		public string workQueueName
		{
			get
			{
				return this._workQueueName;
			}
			set
			{
				this._workQueueName = value;
			}
		}
		public string workQueueStatus
		{
			get
			{
				return this._workQueueStatus;
			}
			set
			{
				this._workQueueStatus = value;
			}
		}
		public string workQueueSequence
		{
			get
			{
				return this._workQueueSequence;
			}
			set
			{
				this._workQueueSequence = value;
			}
		}
		public string workQueueType
		{
			get
			{
				return this._workQueueType;
			}
			set
			{
				this._workQueueType = value;
			}
		}
		public string pointOfWorkName
		{
			get
			{
				return this._pointOfWorkName;
			}
			set
			{
				this._pointOfWorkName = value;
			}
		}
		public string load_mode
		{
			get
			{
				return this._load_mode;
			}
			set
			{
				this._load_mode = value;
			}
		}
		public System.Nullable<System.Int64> SOURCE_TS_MS
		{
			get
			{
				return this._SOURCE_TS_MS;
			}
			set
			{
				this._SOURCE_TS_MS = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.eventType;
			case 1: return this.opType;
			case 2: return this.cdhTerminalCode;
			case 3: return this.messageSequenceNumber;
			case 4: return this.workQueueId;
			case 5: return this.vesselVisitId;
			case 6: return this.vesselName;
			case 7: return this.vesselRow;
			case 8: return this.vesselDeck;
			case 9: return this.workQueueName;
			case 10: return this.workQueueStatus;
			case 11: return this.workQueueSequence;
			case 12: return this.workQueueType;
			case 13: return this.pointOfWorkName;
			case 14: return this.load_mode;
			case 15: return this.SOURCE_TS_MS;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.eventType = (System.String)fieldValue; break;
			case 1: this.opType = (System.String)fieldValue; break;
			case 2: this.cdhTerminalCode = (System.String)fieldValue; break;
			case 3: this.messageSequenceNumber = (System.Nullable<System.Int64>)fieldValue; break;
			case 4: this.workQueueId = (System.Nullable<System.Int64>)fieldValue; break;
			case 5: this.vesselVisitId = (System.String)fieldValue; break;
			case 6: this.vesselName = (System.String)fieldValue; break;
			case 7: this.vesselRow = (System.String)fieldValue; break;
			case 8: this.vesselDeck = (System.String)fieldValue; break;
			case 9: this.workQueueName = (System.String)fieldValue; break;
			case 10: this.workQueueStatus = (System.String)fieldValue; break;
			case 11: this.workQueueSequence = (System.String)fieldValue; break;
			case 12: this.workQueueType = (System.String)fieldValue; break;
			case 13: this.pointOfWorkName = (System.String)fieldValue; break;
			case 14: this.load_mode = (System.String)fieldValue; break;
			case 15: this.SOURCE_TS_MS = (System.Nullable<System.Int64>)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
